language: r
sudo: false
cache: packages

pandoc_version: 1.19.2.1

r_packages:
    - bookdown

script:
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  local_dir: _book
  on:
    branch: master
