language: r
sudo: false
cache: packages

pandoc_version: 1.17.2

script:
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  on:
    branch: master
